# Revisão de código 

Olá! 

Meu nome é Suelen. Estou feliz em revisar seu projeto hoje!

Quando vejo um erro pela primeira vez, apenas aponto. Deixarei você encontrá-lo e corrigi-lo sozinho. Além disso, ao longo do texto, farei algumas observações sobre melhorias no código e também farei comentários sobre suas percepções sobre o assunto. Mas se você ainda não consegue lidar com essa tarefa, darei uma dica mais precisa na próxima iteração e também alguns exemplos práticos. Estarei aberta a feedbacks e discussões sobre o tema.

Você pode encontrar meus comentários em caixas verdes, amarelas ou vermelhas como estas:


<div class="alert alert-block alert-success">
<b>Comentário: </b> <a class="tocSkip"></a>

Sucesso. Tudo está correto.
</div>

<div class="alert alert-block alert-warning">
<b>Comentário: </b> <a class="tocSkip"></a>

Observações. Algumas recomendações.
</div>

<div class="alert alert-block alert-danger">

<b>Comentário: </b> <a class="tocSkip"></a>

O bloco requer algumas correções. O trabalho não pode ser aceito com os comentários vermelhos.
</div>

Você pode me responder usando isto:

<div class="alert alert-block alert-info">
<b>Resposta do aluno</b> <a class="tocSkip"></a>
</div>

<div class="alert alert-block alert-success">
<b>Comentário geral: </b> <a class="tocSkip"></a>

Parabéns pela conclusão do projeto, Ricardo!👏🚀

O seu trabalho demonstra alta qualidade, com código bem estruturado e comentários relevantes em cada etapa. 

O projeto está aprovado! Continue com o excelente trabalho!

</div>

In [35]:
#Importando as bibliotecas
import pandas as pd
import plotly.express as px
import numpy as np
from scipy import stats as st
import plotly.graph_objects as go

In [2]:
#Carregando DataFrame das viagens
trips_amount = pd.read_csv('..\data\moved_project_sql_result_01.csv')
trips_amount

                                 company_name  trips_amount
0                                   Flash Cab         19558
1                   Taxi Affiliation Services         11422
2                            Medallion Leasin         10367
3                                  Yellow Cab          9888
4             Taxi Affiliation Service Yellow          9299
..                                        ...           ...
59               4053 - 40193 Adwar H. Nikola             7
60                    2733 - 74600 Benny Jona             7
61              5874 - 73628 Sergey Cab Corp.             5
62  2241 - 44667 - Felman Corp, Manuel Alonso             3
63                3556 - 36214 RC Andrews Cab             2

[64 rows x 2 columns]

In [3]:
#Carregando DataFrame das saídas e média das viagens
dropoff_trips = pd.read_csv('..\data\moved_project_sql_result_04.csv')
dropoff_trips

   dropoff_location_name  average_trips
0                   Loop   10727.466667
1            River North    9523.666667
2          Streeterville    6664.666667
3              West Loop    5163.666667
4                 O'Hare    2546.900000
..                   ...            ...
89       Mount Greenwood       3.137931
90             Hegewisch       3.117647
91              Burnside       2.333333
92             East Side       1.961538
93             Riverdale       1.800000

[94 rows x 2 columns]

<div class="alert alert-block alert-success">
<b>Comentário: </b> <a class="tocSkip"></a>
    
Dados foram carregados e processados com sucesso!

In [4]:
#Verificando as características do DataFrame
trips_amount.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_name  64 non-null     str
 1   trips_amount  64 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [5]:
#Verificando as características do DataFrame
dropoff_trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dropoff_location_name  94 non-null     str
 1   average_trips          94 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.6 KB

In [6]:
#Verificando se há dados nulos
print((trips_amount.isna().sum()), (dropoff_trips.isna().sum()))

company_name    0
trips_amount    0
dtype: int64 dropoff_location_name    0
average_trips            0
dtype: int64

In [7]:
#Verificando se há dados duplicados
print((trips_amount.duplicated().sum()), (dropoff_trips.isna().sum()))

0 dropoff_location_name    0
average_trips            0
dtype: int64

In [8]:
#Agrupando o número de viagens
top10_neighborhood = dropoff_trips.groupby(['dropoff_location_name'], as_index=False).sum()
top10_neighborhood.sort_values(by='average_trips', axis=0, ascending=False, inplace=True)
print(top10_neighborhood.columns)

Index(['dropoff_location_name', 'average_trips'], dtype='str')

In [41]:
#Criando gráfico dos 10 bairros mais visitados

fig = px.bar(top10_neighborhood.head(10),
             x='dropoff_location_name',
             y='average_trips',
            color='average_trips')
fig.update_layout(title='Top 10 most visited neighborhoods')
fig.update_layout(xaxis_title='Neighborhood name', yaxis_title='Average trips')
fig.show()

In [10]:
#Todas as corridas são para locais turísticos de Chicago, 
#a única 'exceção' é o aeroporto O'Hare.
#Vale notar também, que os 4 primeiros resultados são de locais perto do litoral de Chicago

In [11]:
#Agrupando número de viagens por empresa
empresa_viagens = trips_amount.groupby(['company_name'], as_index=False)['trips_amount'].sum()
empresa_viagens.sort_values(by='trips_amount', axis=0, ascending=False, inplace=True)
empresa_viagens.head(10)

                         company_name  trips_amount
45                          Flash Cab         19558
61          Taxi Affiliation Services         11422
50                   Medallion Leasin         10367
63                         Yellow Cab          9888
60    Taxi Affiliation Service Yellow          9299
36          Chicago Carriage Cab Corp          9181
43                       City Service          8448
59                           Sun Taxi          7701
58          Star North Management LLC          7455
33  Blue Ribbon Taxi Association Inc.          5953

In [42]:
#Criando gráfico com o top 10 das empresas com mais corridas

fig = px.bar(empresa_viagens.head(10), x='company_name', y='trips_amount', color='trips_amount')
fig.update_layout(title='Top 10 companies with more trips')
fig.update_layout(xaxis_title='Company name', yaxis_title='Trips amount')
fig.show()

In [13]:
#Nota-se um grande número de corridas na companhia da Flash Cab,
#enquanto todas as outras companhias de taxi são bem similares nos números de corridas

In [14]:
#Carregando os dados da consulta 07
trips_ohare = pd.read_csv('..\data\moved_project_sql_result_07.csv')
trips_ohare.head()

              start_ts weather_conditions  duration_seconds
0  2017-11-25 16:00:00               Good            2410.0
1  2017-11-25 14:00:00               Good            1920.0
2  2017-11-25 12:00:00               Good            1543.0
3  2017-11-04 10:00:00               Good            2512.0
4  2017-11-11 07:00:00               Good            1440.0

<div class="alert alert-block alert-success">
<b>Comentário: </b> <a class="tocSkip"></a>
    
- Todas as análises e gráficos estão corretos. Parabéns!
- Foram adicionados comentários relevantes para análise.
</div>

In [15]:
#Verificando as características do DataFrame
trips_ohare.info()

<class 'pandas.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   start_ts            1068 non-null   str
 1   weather_conditions  1068 non-null   str
 2   duration_seconds    1068 non-null   float64
dtypes: float64(1), str(2)
memory usage: 25.2 KB

In [16]:
trips_ohare.head()

              start_ts weather_conditions  duration_seconds
0  2017-11-25 16:00:00               Good            2410.0
1  2017-11-25 14:00:00               Good            1920.0
2  2017-11-25 12:00:00               Good            1543.0
3  2017-11-04 10:00:00               Good            2512.0
4  2017-11-11 07:00:00               Good            1440.0

In [17]:
#Verificando se há duplicatas
trips_ohare.duplicated().sum()

np.int64(197)

In [18]:
#Dropando os dados duplicados
trips_ohare.drop_duplicates(inplace=True)
trips_ohare.duplicated().sum()

np.int64(0)

In [19]:
trips_ohare['weekday'] = pd.to_datetime(trips_ohare['start_ts']).dt.day_name()
trips_ohare[trips_ohare['weekday'] != 'Saturday'].head()

Empty DataFrame
Columns: [start_ts, weather_conditions, duration_seconds, weekday]
Index: []

In [20]:
#Agrupando os dias não chuvosos em uma variável nova
good_weather = trips_ohare[(trips_ohare['weather_conditions'] == 'Good') & (trips_ohare['weekday'] == 'Saturday')]
good_weather.head()

              start_ts weather_conditions  duration_seconds   weekday
0  2017-11-25 16:00:00               Good            2410.0  Saturday
1  2017-11-25 14:00:00               Good            1920.0  Saturday
2  2017-11-25 12:00:00               Good            1543.0  Saturday
3  2017-11-04 10:00:00               Good            2512.0  Saturday
4  2017-11-11 07:00:00               Good            1440.0  Saturday

In [21]:
#Agrupando o dias chuvosos em uma nova variável
bad_weather = trips_ohare[(trips_ohare['weather_conditions'] == 'Bad') & (trips_ohare['weekday'] == 'Saturday')]
bad_weather.head()

               start_ts weather_conditions  duration_seconds   weekday
6   2017-11-04 16:00:00                Bad            2969.0  Saturday
30  2017-11-18 12:00:00                Bad            1980.0  Saturday
34  2017-11-04 17:00:00                Bad            2460.0  Saturday
51  2017-11-04 16:00:00                Bad            2760.0  Saturday
52  2017-11-18 12:00:00                Bad            2460.0  Saturday

In [22]:
#Criando uma coluna com o total de minutos para facilitar a visualização do tempo
good_weather['duration_minutes'] = (trips_ohare['duration_seconds'] / 60).round(1)
good_weather.head()

,start_ts,weather_conditions,duration_seconds,weekday,duration_minutes
0,2017-11-25 16:00:00,Good,2410.0,Saturday,40.2
1,2017-11-25 14:00:00,Good,1920.0,Saturday,32.0
2,2017-11-25 12:00:00,Good,1543.0,Saturday,25.7
3,2017-11-04 10:00:00,Good,2512.0,Saturday,41.9
4,2017-11-11 07:00:00,Good,1440.0,Saturday,24.0

In [23]:
#Criando uma coluna com o total de minutos para facilitar a visualização do tempo
bad_weather['duration_minutes'] = (trips_ohare['duration_seconds'] / 60).round(1)
bad_weather.head()

,start_ts,weather_conditions,duration_seconds,weekday,duration_minutes
6,2017-11-04 16:00:00,Bad,2969.0,Saturday,49.5
30,2017-11-18 12:00:00,Bad,1980.0,Saturday,33.0
34,2017-11-04 17:00:00,Bad,2460.0,Saturday,41.0
51,2017-11-04 16:00:00,Bad,2760.0,Saturday,46.0
52,2017-11-18 12:00:00,Bad,2460.0,Saturday,41.0

In [37]:
bad_weather.shape, good_weather.shape

((148, 5), (723, 5))

In [24]:
#Fazendo o teste da hipótese

alpha = 0.5
results = st.ttest_ind(good_weather['duration_minutes'],
                         bad_weather['duration_minutes'])
print('valor-p: ', results.pvalue)

if (results.pvalue < alpha):
    print('Rejeitamos a hipótese nula')
else:
    print('Não podemos rejeitar a hipótese nula')

valor-p:  7.390771543391882e-08
Rejeitamos a hipótese nula

In [25]:
#Com o teste realizado, obtivemos um valor-p extremamente baixo, por isso,
#podemos rejeitar a hipótese nula, o que significa que a chuva afeta na duração
#das corridas de taxi.
#Escolhi o valor alpha como 0.05 por não ser algo que necessite de uma enorme precisão,
#até porque o resultado não mudaria pelo o valor-p ser tão pequeno.

<div class="alert alert-block alert-warning">
<b>Comentário: </b> <a class="tocSkip"></a>

Teste realizado corretamente. No entanto, era necessário filtrar o dataframe para utilizar apenas os dias de sábado.

Exemplo: 

```python
# Criar variável para dias de sábado
loop_ohare_trips['weekday'] = loop_ohare_trips['start_ts'].dt.dayofweek  # 0=segunda, 5=sábado
saturday_trips = loop_ohare_trips[loop_ohare_trips['weekday'] == 5]
```

In [27]:
print('Média dos dias chuvosos: ', bad_weather['duration_minutes'].mean().round(1))
print('Média dos dias não chuvosos: ', good_weather['duration_minutes'].mean().round(1))

Média dos dias chuvosos:  40.2
Média dos dias não chuvosos:  33.9

In [46]:
IQR = np.percentile(good_weather['duration_minutes'], 75) - np.percentile(good_weather['duration_minutes'], 25)
print('IQR: ', IQR)

IQR:  17.6

In [47]:
bin_width = 2 * IQR / (len(good_weather['duration_minutes']) ** (1/3))
print('Bin width: ', bin_width)

Bin width:  3.921900437804374

In [52]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=good_weather['duration_minutes'], nbinsx=26, name='Non rainy days'))
fig.add_trace(go.Histogram(x=bad_weather['duration_minutes'], nbinsx=26, name='Rainy days'))
fig.update_layout(title='Distribution of trip duration in minutes for rainy and non rainy days')
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=0.75)
fig.show()

In [51]:
print(int(np.ceil((good_weather['duration_minutes'].max() - good_weather['duration_minutes'].min()) / bin_width)))
print(int(np.ceil((bad_weather['duration_minutes'].max() - bad_weather['duration_minutes'].min()) / bin_width)))

32
20